/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-05-21 01:38:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class restricted_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/extras/fonte-awesome.min.css\">\r\n");
      out.write("<script src=\"../bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../bootstrap/extras/highcharts.js\"></script>\r\n");
      out.write("<script src=\"../bootstrap/extras/highcharts-more.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/extras/admin.css\">\r\n");
      out.write("<script src=\"../bootstrap/extras/admin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Painel Administrativo</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"jumbotron\">\r\n");
      out.write("\t    <div class=\"panel-header\">\r\n");
      out.write("\t\t\t<h1 class=\"main-header\">Bem vindo ao Painel Administrativo!</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\">\r\n");
      out.write("\t    \r\n");
      out.write("\t    <h3>Main customers</h3>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <table class=\"table table-condensed table-bordered table-hover small\">\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t           <tr>\r\n");
      out.write("\t               <th style=\"width:80px;\">.</th>\r\n");
      out.write("\t               <th>Name</th>\r\n");
      out.write("\t               <th>Revenue</th>\r\n");
      out.write("\t               <th>Tax</th>\r\n");
      out.write("\t               <th>Cap</th>\r\n");
      out.write("\t               <th>ROI</th>\t               \r\n");
      out.write("\t               <th>Interest</th>\r\n");
      out.write("\t           </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t        <tbody>\r\n");
      out.write("\t            \r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-dashboard\"></i></a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-eye-open\"></i></a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-warning-sign\"></i></a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Company 1\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    $ 350 k\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    4 \r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    $ 291,75\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>3,72</td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    3,65%\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                \r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            \r\n");
      out.write("\t            <tr class=\"danger\">\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-dashboard\"></i> </a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-eye-open\"></i> </a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-warning-sign\"></i></a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Customer 2\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>$ 270 k</td>\r\n");
      out.write("\t                <td>7,8 </td>\r\n");
      out.write("\t                <td>$ 1307.32</td>\r\n");
      out.write("\t                <td>2,61</td>\t                \r\n");
      out.write("\t                <td>8,45%</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\r\n");
      out.write("\t            <tr class=\"info\">\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-dashboard\"></i> </a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-eye-open\"></i> </a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-warning-sign\"></i></a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Customer 3\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>$ 125 k</td>\r\n");
      out.write("\t                <td>2,5 </td>\r\n");
      out.write("\t                <td>$ 312.45</td>\r\n");
      out.write("\t                <td>9,21</td>\t                \r\n");
      out.write("\t                <td>2,5%</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\r\n");
      out.write("\t            <tr >\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-dashboard\"></i> </a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-eye-open\"></i> </a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-warning-sign\"></i></a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Customer 4\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>$ 205 k</td>\r\n");
      out.write("\t                <td>7,1 </td>\r\n");
      out.write("\t                <td>$ 115,75</td>\r\n");
      out.write("\t                <td>6,27</td>\r\n");
      out.write("\t                <td>(n/d)</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\r\n");
      out.write("\t            \r\n");
      out.write("\t        </tbody>\r\n");
      out.write("\t        \r\n");
      out.write("\t    </table>\r\n");
      out.write("\t    \r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\">\r\n");
      out.write("\t    <div id='grafico1' class=\"grafico\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\">\r\n");
      out.write("\t    <div id='grafico2' class=\"grafico\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-md-6\">\r\n");
      out.write("\t    <div id='grafico3' class=\"grafico\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t    \r\n");
      out.write("\t    <h3>Messages</h3>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <table class=\"table table-condensed table-bordered table-hover small\">\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t           <tr>\r\n");
      out.write("\t               <th style=\"width:30px;\">.</th>\r\n");
      out.write("\t               <th>From</th>\r\n");
      out.write("\t               <th>Subject</th>\r\n");
      out.write("\t               <th>Actions</th>\r\n");
      out.write("\t           </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t        <tbody>\r\n");
      out.write("\t            \r\n");
      out.write("\t          \r\n");
      out.write("\t            \r\n");
      out.write("\t            \r\n");
      out.write("\t            <tr class=\"text-info\">\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                   <i class=\"glyphicon glyphicon-info-sign\"></i>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                   John Doe\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Complaint\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-eye-open\"></i></a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-arrow-right\"></i> </a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            \r\n");
      out.write("\r\n");
      out.write("\t            <tr class=\"text-info\">\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                   <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Mr Joe\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    Congrats\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-eye-open\"></i></a>\r\n");
      out.write("\t                    <a href=\"#\"> <i class=\"glyphicon glyphicon-arrow-right\"></i> </a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            \r\n");
      out.write("\r\n");
      out.write("\t            \r\n");
      out.write("\t        </tbody>\r\n");
      out.write("\t        \r\n");
      out.write("\t    </table>\r\n");
      out.write("\t    \r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t    \t<div id='grafico4' class=\"grafico\" style=\"height: 400px;\"></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
