/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-05-21 15:24:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*\r\n");
      out.write(" * Specific styles of signin component\r\n");
      out.write(" */\r\n");
      out.write("/*\r\n");
      out.write(" * General styles\r\n");
      out.write(" */\r\n");
      out.write("body, html {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-container.card {\r\n");
      out.write("    max-width: 350px;\r\n");
      out.write("    padding: 40px 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    -moz-user-select: none;\r\n");
      out.write("    -webkit-user-select: none;\r\n");
      out.write("    user-select: none;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * Card component\r\n");
      out.write(" */\r\n");
      out.write(".card {\r\n");
      out.write("    background-color: #F7F7F7;\r\n");
      out.write("    /* just in case there no content*/\r\n");
      out.write("    padding: 20px 25px 30px;\r\n");
      out.write("    margin: 0 auto 25px;\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("    /* shadows and rounded borders */\r\n");
      out.write("    -moz-border-radius: 2px;\r\n");
      out.write("    -webkit-border-radius: 2px;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-img-card {\r\n");
      out.write("    width: 96px;\r\n");
      out.write("    height: 96px;\r\n");
      out.write("    margin: 0 auto 10px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    -moz-border-radius: 50%;\r\n");
      out.write("    -webkit-border-radius: 50%;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * Form styles\r\n");
      out.write(" */\r\n");
      out.write(".profile-name-card {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 10px 0 0;\r\n");
      out.write("    min-height: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reauth-email {\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #404040;\r\n");
      out.write("    line-height: 2;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin #inputEmail,\r\n");
      out.write(".form-signin #inputPassword {\r\n");
      out.write("    direction: ltr;\r\n");
      out.write("    height: 44px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin input[type=email],\r\n");
      out.write(".form-signin input[type=password],\r\n");
      out.write(".form-signin input[type=text],\r\n");
      out.write(".form-signin button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin .form-control:focus {\r\n");
      out.write("    border-color: rgb(104, 145, 162);\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);\r\n");
      out.write("    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn.btn-signin {\r\n");
      out.write("    /*background-color: #4d90fe; */\r\n");
      out.write("    background-color: rgb(104, 145, 162);\r\n");
      out.write("    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    -moz-border-radius: 3px;\r\n");
      out.write("    -webkit-border-radius: 3px;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    -o-transition: all 0.218s;\r\n");
      out.write("    -moz-transition: all 0.218s;\r\n");
      out.write("    -webkit-transition: all 0.218s;\r\n");
      out.write("    transition: all 0.218s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn.btn-signin:hover,\r\n");
      out.write(".btn.btn-signin:active,\r\n");
      out.write(".btn.btn-signin:focus {\r\n");
      out.write("    background-color: rgb(12, 97, 33);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".forgot-password {\r\n");
      out.write("    color: rgb(104, 145, 162);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".forgot-password:hover,\r\n");
      out.write(".forgot-password:active,\r\n");
      out.write(".forgot-password:focus{\r\n");
      out.write("    color: rgb(12, 97, 33);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("    // DOM ready\r\n");
      out.write("\r\n");
      out.write("    // Test data\r\n");
      out.write("    /*\r\n");
      out.write("     * To test the script you should discomment the function\r\n");
      out.write("     * testLocalStorageData and refresh the page. The function\r\n");
      out.write("     * will load some test data and the loadProfile\r\n");
      out.write("     * will do the changes in the UI\r\n");
      out.write("     */\r\n");
      out.write("    // testLocalStorageData();\r\n");
      out.write("    // Load profile if it exits\r\n");
      out.write("    loadProfile();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * Function that gets the data of the profile in case\r\n");
      out.write(" * thar it has already saved in localstorage. Only the\r\n");
      out.write(" * UI will be update in case that all data is available\r\n");
      out.write(" *\r\n");
      out.write(" * A not existing key in localstorage return null\r\n");
      out.write(" *\r\n");
      out.write(" */\r\n");
      out.write("function getLocalProfile(callback){\r\n");
      out.write("    var profileImgSrc      = localStorage.getItem(\"PROFILE_IMG_SRC\");\r\n");
      out.write("    var profileName        = localStorage.getItem(\"PROFILE_NAME\");\r\n");
      out.write("    var profileReAuthEmail = localStorage.getItem(\"PROFILE_REAUTH_EMAIL\");\r\n");
      out.write("\r\n");
      out.write("    if(profileName !== null\r\n");
      out.write("            && profileReAuthEmail !== null\r\n");
      out.write("            && profileImgSrc !== null) {\r\n");
      out.write("        callback(profileImgSrc, profileName, profileReAuthEmail);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * Main function that load the profile if exists\r\n");
      out.write(" * in localstorage\r\n");
      out.write(" */\r\n");
      out.write("function loadProfile() {\r\n");
      out.write("    if(!supportsHTML5Storage()) { return false; }\r\n");
      out.write("    // we have to provide to the callback the basic\r\n");
      out.write("    // information to set the profile\r\n");
      out.write("    getLocalProfile(function(profileImgSrc, profileName, profileReAuthEmail) {\r\n");
      out.write("        //changes in the UI\r\n");
      out.write("        $(\"#profile-img\").attr(\"src\",profileImgSrc);\r\n");
      out.write("        $(\"#profile-name\").html(profileName);\r\n");
      out.write("        $(\"#reauth-email\").html(profileReAuthEmail);\r\n");
      out.write("        $(\"#inputEmail\").hide();\r\n");
      out.write("        $(\"#remember\").hide();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * function that checks if the browser supports HTML5\r\n");
      out.write(" * local storage\r\n");
      out.write(" *\r\n");
      out.write(" * @returns {boolean}\r\n");
      out.write(" */\r\n");
      out.write("function supportsHTML5Storage() {\r\n");
      out.write("    try {\r\n");
      out.write("        return 'localStorage' in window && window['localStorage'] !== null;\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * Test data. This data will be safe by the web app\r\n");
      out.write(" * in the first successful login of a auth user.\r\n");
      out.write(" * To Test the scripts, delete the localstorage data\r\n");
      out.write(" * and comment this call.\r\n");
      out.write(" *\r\n");
      out.write(" * @returns {boolean}\r\n");
      out.write(" */\r\n");
      out.write("function testLocalStorageData() {\r\n");
      out.write("    if(!supportsHTML5Storage()) { return false; }\r\n");
      out.write("    localStorage.setItem(\"PROFILE_IMG_SRC\", \"//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120\" );\r\n");
      out.write("    localStorage.setItem(\"PROFILE_NAME\", \"César Izquierdo Tello\");\r\n");
      out.write("    localStorage.setItem(\"PROFILE_REAUTH_EMAIL\", \"oneaccount@gmail.com\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("        <div class=\"card card-container\">\r\n");
      out.write("            <!-- <img class=\"profile-img-card\" src=\"//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120\" alt=\"\" /> -->\r\n");
      out.write("            <img id=\"profile-img\" class=\"profile-img-card\" src=\"//ssl.gstatic.com/accounts/ui/avatar_2x.png\" />\r\n");
      out.write("            <p id=\"profile-name\" class=\"profile-name-card\"></p>\r\n");
      out.write("            \r\n");
      out.write("            <form class=\"form-signin\" action=\"j_security_check\" method=\"post\">\r\n");
      out.write("                <span id=\"reauth-email\" class=\"reauth-email\"></span>\r\n");
      out.write("                <input id=\"j_username\" name=\"j_username\" type=\"text\" placeholder=\"Usuário\" class=\"form-control\">\r\n");
      out.write("                <input id=\"j_password\" name=\"j_password\" type=\"password\" placeholder=\"Senha\" class=\"form-control\">\r\n");
      out.write("                \r\n");
      out.write("               \t<input class=\"btn btn-lg btn-primary btn-block btn-signin\" type=\"submit\" value=\"Enviar\">\r\n");
      out.write("            </form><!-- /form -->\r\n");
      out.write("        </div><!-- /card-container -->\r\n");
      out.write("    </div><!-- /container -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
